### ISSUE TITLE
Restrict the node number in node breaker view

### ISSUE THREAD

**Issue by flo-dup** [powsybl/powsybl-core#1845]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
When creating a new node in a node breaker view, there is no restriction on the int number provided:
   - if very large, will create a unnecessary large array or even produce a OutOfMemoryError
   - if negative, the vertex created cannot be found after creation: it is created but at the index of the vertices size

* **What is the expected behavior?**
Restrict the node number to [0, max], where max=?

* **What is the motivation / use case for changing the behavior?**
Avoid misuse of node number

**Comment by leblowl** [comment]
It looks like the NodeBreakerVoltageLevel class uses an UndirectedGraphImpl and
contains a few methods that add nodes to this graph, which is where errors can occur:
- https://github.com/powsybl/powsybl-core/blob/76d5a4b8e209837cb8b4d612b9b5edca2365a0b5/iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java#L146
- https://github.com/powsybl/powsybl-core/blob/76d5a4b8e209837cb8b4d612b9b5edca2365a0b5/iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java#L188
- https://github.com/powsybl/powsybl-core/blob/76d5a4b8e209837cb8b4d612b9b5edca2365a0b5/iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java#L963

These methods already have some validation related to the nodes so this could be
a good place to add additional validation. We could create a configurable node
limit as a property on the NodeBreakerVoltageLevel class, unless there is
another configuration pattern used.

For negative values, we could add validation in the same place. We can also add
validation to the graph implementation in `addVertexIfNotPresent`, since maybe
`-1` shouldn't be accepted under any usage of the graph, but I think it would be
user friendly to catch those exceptions in NodeBreakerVoltageLevel so more
context-specific error messages can be provided.

What do you think of this approach?

**Comment by flo-dup** [comment]
Well, at first I was thinking to only add validation directly in `addVertexIfNotPresent`, as there's not so much difference between the 3 calls to this method. I mean, the point is that in all 3 cases there's a vertex with a high number in the network, and the fact that we realize it when adding a terminal, a Switch or an InternalConnection does not really matter I think.

About the node limit, we could put it as a property on the NodeBreakerVoltageLevel class indeed, with a default value to about 1000 I'd say (do you agree on that value @geofjamg?). And I think if someone needs to deal with really large voltage levels (or badly numbered vertices), he could override it using the `PlatformConfig`. Not sure the use of PlatformConfig is straightforward, so don't hesitate to ask, but below's an example:

https://github.com/powsybl/powsybl-core/blob/76d5a4b8e209837cb8b4d612b9b5edca2365a0b5/time-series/time-series-api/src/main/java/com/powsybl/timeseries/ast/NodeCalcVisitors.java#L30-L33

**Comment by leblowl** [comment]
I think that sounds great!
